/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import com.asgard.core.annotation.AnchorPoint
import com.asgard.core.lifecycle.use
import com.asgard.core.out.impl.console.SimpleConsoleOutFactory
import com.glassthought.tmux.TmuxCommunicatorImpl
import com.glassthought.tmux.TmuxSessionManager
import com.glassthought.tmux.util.TmuxCommandRunner
import kotlinx.coroutines.runBlocking


// NOTE: Run via the installed distribution for interactive mode to work.
// `./gradlew :app:run` does NOT work — Gradle wraps the JVM without a real controlling
// terminal, breaking isatty() checks in interactive programs like `claude`.
//
// To run:
//   ./gradlew :app:installDist
//   ./app/build/install/app/bin/app
@AnchorPoint("ap.4JVSSyLwZXop6hWiJNYevFQX.E")
fun main() {

  // [runBlocking] is acceptable at main() entry points per Kotlin development standards.
  runBlocking {
    SimpleConsoleOutFactory.standard().use { outFactory ->
      val commandRunner = TmuxCommandRunner()
      val communicator = TmuxCommunicatorImpl(outFactory, commandRunner)
      val sessionManager = TmuxSessionManager(outFactory, commandRunner, communicator)

      val sessionName = "agent-harness__${System.currentTimeMillis()}"
      println("Tmux session name: $sessionName")

      val session = sessionManager.createSession(sessionName, "claude")

      // tmux buffers keystrokes, so we can send immediately.
      session.sendKeys("Write 'hello world from tmux' to /tmp/out")

      // The tmux session is intentionally left alive after main() exits.
      // Claude needs time to process the prompt. The user can attach to the session
      // via `tmux attach -t <sessionName>` to observe progress, or kill it manually.
    }
  }
}
