/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import com.asgard.core.lifecycle.use
import com.asgard.core.out.impl.console.SimpleConsoleOutFactory
import kotlinx.coroutines.runBlocking

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

// NOTE: Run via the installed distribution for interactive mode to work.
// `./gradlew :app:run` does NOT work — Gradle wraps the JVM without a real controlling
// terminal, breaking isatty() checks in interactive programs like `claude`.
//
// To run:
//   ./gradlew :app:installDist
//   ./app/build/install/app/bin/app
fun main() {
    println(App().greeting)

    // [runBlocking] is acceptable at main() entry points per Kotlin development standards.
    runBlocking {
        SimpleConsoleOutFactory.standard().use { outFactory ->
            val sessionManager = TmuxSessionManager(outFactory)
            val communicator = TmuxCommunicator(outFactory)

            val sessionName = "agent-harness__${System.currentTimeMillis()}"
            println("Tmux session name: $sessionName")

            val session = sessionManager.createSession(sessionName, "claude")

            // tmux buffers keystrokes, so we can send immediately.
            communicator.sendKeys(session, "Write 'hello world from tmux' to /tmp/out")
        }
    }
}
