/*
 * This source file was generated by the Gradle 'init' task
 */
package com.glassthought.chainsaw.cli

import com.asgard.core.annotation.AnchorPoint
import com.asgard.core.lifecycle.use
import com.glassthought.chainsaw.core.initializer.InitializerImpl
import kotlinx.coroutines.runBlocking


// NOTE: Run via the installed distribution for interactive mode to work.
// `./gradlew :app:run` does NOT work — Gradle wraps the JVM without a real controlling
// terminal, breaking isatty() checks in interactive programs like `claude`.
//
// To run:
//   ./gradlew :app:installDist
//   ./app/build/install/app/bin/app
@AnchorPoint("ap.4JVSSyLwZXop6hWiJNYevFQX.E")
fun main() {
  val deps = InitializerImpl().initialize()

  // [runBlocking] is acceptable at main() entry points per Kotlin development standards.
  runBlocking {
    deps.use { _ ->
      val sessionName = "agent-harness__${System.currentTimeMillis()}"
      println("Tmux session name: $sessionName")

      val session = deps.tmuxSessionManager.createSession(sessionName, "claude")

      // tmux buffers keystrokes, so we can send immediately.
      session.sendKeys("Write 'hello world from tmux' to /tmp/out")

      // The tmux session is intentionally left alive after main() exits.
      // Claude needs time to process the prompt. The user can attach to the session
      // via `tmux attach -t <sessionName>` to observe progress, or kill it manually.
    }
  }
}
