/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // asgardTestTools provides AsgardDescribeSpec (Kotest DescribeSpec extension).
    // Kotest deps (assertions, runner) are 'implementation' in asgardTestTools (not api),
    // so we declare them directly here for compilation visibility.
    testImplementation("com.asgard:asgardTestTools:1.0.0")
    testImplementation(libs.kotest.assertions.core)
    testImplementation(libs.kotest.runner.junit5)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // AsgardCore: general-purpose foundation library (ProcessRunner, Out logging, etc.)
    implementation("com.asgard:asgardCore:1.0.0")

    // Coroutines: required for runBlocking in main() and suspend ProcessRunner calls
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")

    // OkHttp: HTTP client for direct LLM API calls
    implementation("com.squareup.okhttp3:okhttp:4.12.0")

    // org.json: lightweight JSON construction and parsing for LLM API request/response bodies
    implementation("org.json:json:20240303")

    // snakeyaml: YAML parsing for ticket and role markdown frontmatter
    implementation("org.yaml:snakeyaml:2.2")

    // Jackson: structured JSON deserialization for workflow definition files
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.17.2")

    // MockWebServer: local HTTP server for unit testing OkHttp-based API callers
    testImplementation("com.squareup.okhttp3:mockwebserver:4.12.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.glassthought.chainsaw.cli.AppMainKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()

    // Gradle property -PrunIntegTests=true enables integration tests.
    // Registered as a task input so Gradle cache is invalidated when it changes
    // (unlike env vars, which Gradle does not track).
    val runIntegTests = project.findProperty("runIntegTests")?.toString() == "true"
    inputs.property("runIntegTests", runIntegTests)
    systemProperty("runIntegTests", runIntegTests)
}
