/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application

    // Apply detekt for static analysis
    alias(libs.plugins.detekt)

    // Kover for code coverage reports (run explicitly via coverage.sh, NOT wired to test/build)
    alias(libs.plugins.kover)
}

repositories {
    // asgard libraries are published to maven local via publishAsgardToMavenLocal task.
    // mavenLocal() first: consistent with buildlogic convention and prevents remote
    // artifacts from shadowing locally published ones.
    mavenLocal()
    mavenCentral()
}

dependencies {
    // asgardTestTools provides AsgardDescribeSpec (Kotest DescribeSpec extension).
    // Kotest deps (assertions, runner) are 'implementation' in asgardTestTools (not api),
    // so we declare them directly here for compilation visibility.
    testImplementation(libs.asgard.test.tools)
    testImplementation(libs.kotest.assertions.core)
    testImplementation(libs.kotest.runner.junit5)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.ktor.server.test.host)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // AsgardCore: general-purpose foundation library (ProcessRunner, Out logging, etc.)
    implementation(libs.asgard.core)

    // Coroutines: required for runBlocking in main() and suspend ProcessRunner calls
    implementation(libs.kotlinx.coroutines.core)

    // snakeyaml: YAML parsing for ticket and role markdown frontmatter
    implementation(libs.snakeyaml)

    // Jackson: structured JSON deserialization for workflow definition files
    implementation(libs.jackson.databind)
    implementation(libs.jackson.module.kotlin)

    // picocli: CLI argument parsing for 'shepherd run' command.
    implementation(libs.picocli)

    // Ktor: embedded HTTP server for agent-to-harness communication.
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.cio)
    implementation(libs.ktor.server.content.negotiation)
    implementation(libs.ktor.server.status.pages)
    implementation(libs.ktor.serialization.jackson)

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.glassthought.shepherd.cli.AppMainKt"
}

// NOTE: ensureAsgardInMavenLocal cannot be wired here via dependsOn.
// Gradle resolves maven coordinates (com.asgard:*) at CONFIGURATION time — before any
// task, including ensureAsgardInMavenLocal, gets a chance to run. If asgard libs are
// absent from ~/.m2, Gradle fails at configuration before self-healing can occur.
//
// Self-healing is handled by _prepare_pre_build.sh (ref.ap.gtpABfFlF4RE1SITt7k1P.E),
// which must be called BEFORE invoking ./gradlew. See test.sh and test_with_integ.sh.

// Detekt configuration for static analysis.
detekt {
    // Baseline file allows existing issues to be ignored while preventing new ones.
    // Location: app module directory (can be moved to root for multi-module projects).
    baseline = file("$rootDir/detekt-baseline.xml")

    // Build upon default config but allow project-specific overrides.
    config.setFrom(files("$rootDir/detekt-config.yml"))

    // Parallel execution for faster analysis.
    parallel = true

    // Fail build on any finding (baseline excluded).
    buildUponDefaultConfig = true
    allRules = false
}

// Wire detekt to run as part of test.
// This ensures static analysis runs with ./gradlew :app:test.
tasks.named("test") {
    dependsOn(tasks.named("detekt"))
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()

    // Gradle property -PrunIntegTests=true enables integration tests.
    // Registered as a task input so Gradle cache is invalidated when it changes
    // (unlike env vars, which Gradle does not track).
    val runIntegTests = project.findProperty("runIntegTests")?.toString() == "true"
    inputs.property("runIntegTests", runIntegTests)
    systemProperty("runIntegTests", runIntegTests)
}

// Kover auto-wires koverVerify into check→build lifecycle.
// Disable it so coverage stays an explicit opt-in task (run via coverage.sh).
tasks.matching { it.name.startsWith("koverVerify") || it.name.startsWith("koverCachedVerify") }.configureEach {
    enabled = false
}

// Kover configuration: XML coverage report output to repo-root .out/ directory.
// Kover does not support JSON — XML is its machine-readable format.
// sonar dependsOn koverXmlReport (wired in root build.gradle.kts) so coverage is always fresh.
kover {
    reports {
        // [rootDir]: resolves to repo root, so report lands at <repo>/.out/ (not app/.out/).
        val repoOutDir = rootDir.resolve(".out")

        total {
            xml {
                xmlFile.set(repoOutDir.resolve("coverage.xml"))
            }
        }
    }
}
